### ISSUE TITLE
Move repo to elm-lang/html

### ISSUE THREAD

**Issue by laszlopandy** [evancz/elm-html#52]
* Make it clear that this is an official Elm library
* Make naming consistent with elm-lang/core

**Comment by rtfeldman** [comment]
:+1: Agree that this is a good idea. It plays by different rules than third-party libraries, as `main` is aware of it.

Also on a practical level, it's annoying to have to search [package.elm-lang.org](http://package.elm-lang.org) for this instead of Core Libraries, which have a nicer searching UX. :wink:

**Comment by ranraj** [comment]
Hi Team, 
Kindly update the readme file for this repo changes ticket.
It get started guide in read me is still like as below, It is throwing error.
`elm-package install evancz/elm-html`

Fix : 
Update required `elm-package install elm-lang/html`
